# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-07 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participants',
            fields=[
                ('id_p', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('second_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='partphoto')),
                ('project', models.TextField()),
                ('rent', models.IntegerField()),
            ],
        ),
    ]
