# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-07 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Party_policy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idea', models.TextField()),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('person_name', models.CharField(max_length=50)),
                ('person_family', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('person_info', models.CharField(max_length=50)),
            ],
        ),
    ]
